// Step 3 draft builder — DOES NOT touch the frozen situations_v2_canonical_draft.json.
// Produces a separate review file: situations_v2_step3_draft.json
const fs = require('fs');
const path = require('path');

const frozenPath = path.join(__dirname, '../public/prana-story-generator/phase6-data/situations_v2_canonical_draft.json');
const sourcePath = path.join(__dirname, '../public/prana-story-generator/phase6-data/situations.json');
const outPath = path.join(__dirname, '../public/prana-story-generator/phase6-data/situations_v2_step3_draft.json');

const frozen = JSON.parse(fs.readFileSync(frozenPath, 'utf8'));
const source = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));

const EMOTIONS = [
  { id: "EMO_FRUSTRATED", label: "Frustrated", definition: "Something isn't going their way right now and they want to react immediately." },
  { id: "EMO_ANGRY", label: "Angry", definition: "Feels wronged or treated unfairly and wants to push back." },
  { id: "EMO_SCARED", label: "Scared", definition: "Something feels frightening, right now." },
  { id: "EMO_WORRIED", label: "Worried", definition: "Something might go wrong — anticipating a bad outcome that hasn't happened yet." },
  { id: "EMO_SAD", label: "Sad", definition: "Feeling down about a loss, disappointment, or ending." },
  { id: "EMO_GRIEVING", label: "Missing Someone", definition: "Grief or longing for a person, pet, or connection that's gone or far away." },
  { id: "EMO_EMBARRASSED", label: "Embarrassed", definition: "Self-conscious after a public or exposed moment." },
  { id: "EMO_ASHAMED", label: "Not Good Enough", definition: "Shame or self-doubt about their own worth or ability." },
  { id: "EMO_JEALOUS", label: "Jealous", definition: "Wanting what someone else has." },
  { id: "EMO_LEFT_OUT", label: "Left Out", definition: "Excluded from a group, game, or connection." },
  { id: "EMO_OVERWHELMED", label: "Overwhelmed", definition: "Too much happening at once — sensory or mental overload." },
  { id: "EMO_BORED", label: "Bored", definition: "Nothing to do, low stimulation, hard to settle." },
  { id: "EMO_CRANKY", label: "Tired or Cranky", definition: "Body-state driven irritability — hunger, tiredness, overstimulation." },
  { id: "EMO_NERVOUS", label: "Nervous", definition: "Something important is about to happen — anticipating a performance, test, or unfamiliar event." },
  { id: "EMO_GUILTY", label: "Guilty", definition: "Feels bad about something they did or didn't do." },
  { id: "EMO_CONFUSED_RIGHT_WRONG", label: "Confused About Right and Wrong", definition: "Facing a moral dilemma with no clear answer." },
  { id: "EMO_DISAPPOINTED", label: "Disappointed", definition: "An expectation or plan didn't come through." },
  { id: "EMO_UNSURE", label: "Unsure", definition: "Facing something new or unfamiliar and not sure how to act." },
  { id: "EMO_COMPARING", label: "Comparing Themselves to Others", definition: "Measuring their own worth, looks, or things against someone else's." },
  { id: "EMO_TORN", label: "Torn Between Two Choices", definition: "Caught between two people, loyalties, or choices." }
];

// id -> [parentLabel, [emotionIds]]
const MAP = {
SIT001:["Someone took the toy they were playing with",["EMO_ANGRY","EMO_FRUSTRATED"]],
SIT002:["Screen time ended before they were ready",["EMO_FRUSTRATED","EMO_DISAPPOINTED"]],
SIT003:["Told 'no' without an explanation",["EMO_FRUSTRATED"]],
SIT004:["A sibling got a bigger portion",["EMO_JEALOUS","EMO_FRUSTRATED"]],
SIT005:["Couldn't finish their homework",["EMO_FRUSTRATED"]],
SIT006:["A playdate was suddenly cancelled",["EMO_DISAPPOINTED","EMO_SAD"]],
SIT007:["Someone broke something they built",["EMO_ANGRY","EMO_FRUSTRATED"]],
SIT008:["Being rushed to leave the house",["EMO_FRUSTRATED"]],
SIT009:["Hungry and tired all at once",["EMO_CRANKY"]],
SIT010:["Blamed for something they didn't do",["EMO_ANGRY","EMO_FRUSTRATED"]],
SIT011:["Pushed by another child during play",["EMO_ANGRY","EMO_SCARED"]],
SIT012:["No say in what they had to wear",["EMO_FRUSTRATED"]],
SIT013:["An adult didn't understand what they meant",["EMO_FRUSTRATED"]],
SIT014:["The game froze right before winning",["EMO_FRUSTRATED"]],
SIT015:["Forced to sit still for a long time",["EMO_FRUSTRATED","EMO_BORED"]],
SIT016:["A saved game was lost",["EMO_FRUSTRATED","EMO_SAD"]],
SIT017:["A promised treat was forgotten",["EMO_DISAPPOINTED","EMO_SAD"]],
SIT018:["A sibling told on them unfairly",["EMO_ANGRY","EMO_FRUSTRATED"]],
SIT019:["Their clothes felt scratchy and uncomfortable",["EMO_FRUSTRATED"]],
SIT020:["Kept failing the same game level",["EMO_FRUSTRATED"]],
SIT021:["Scared of the dark",["EMO_SCARED"]],
SIT022:["Startled by thunder",["EMO_SCARED"]],
SIT023:["Thought there was a monster under the bed",["EMO_SCARED"]],
SIT024:["A parent leaving for a long trip",["EMO_SAD","EMO_WORRIED"]],
SIT025:["Nervous before going on stage",["EMO_NERVOUS"]],
SIT026:["Anxious before a big test",["EMO_NERVOUS","EMO_WORRIED"]],
SIT027:["Scared of getting a shot at the doctor",["EMO_SCARED"]],
SIT028:["Meeting an unfamiliar adult",["EMO_UNSURE","EMO_SCARED"]],
SIT029:["Got separated from a parent in a crowd",["EMO_SCARED"]],
SIT030:["Accidentally saw something scary online",["EMO_SCARED"]],
SIT031:["Heard grown-ups talk about war on the news",["EMO_WORRIED","EMO_SCARED"]],
SIT032:["Saw news about a flood",["EMO_WORRIED","EMO_SCARED"]],
SIT033:["Worried a parent might get sick",["EMO_WORRIED"]],
SIT034:["Overheard grown-ups worry about money",["EMO_WORRIED"]],
SIT035:["Can't stop imagining what could go wrong",["EMO_WORRIED"]],
SIT036:["Afraid the class will laugh at them",["EMO_NERVOUS","EMO_SCARED"]],
SIT038:["Afraid of a dog nearby",["EMO_SCARED"]],
SIT039:["Scared to try again after a fall",["EMO_SCARED","EMO_UNSURE"]],
SIT040:["Worried a teacher will be angry",["EMO_WORRIED","EMO_SCARED"]],
SIT042:["A friend didn't want to play with them today",["EMO_SAD","EMO_LEFT_OUT"]],
SIT043:["Their pet died",["EMO_GRIEVING","EMO_SAD"]],
SIT044:["A family member died",["EMO_GRIEVING","EMO_SAD"]],
SIT045:["Lost their favourite toy or blanket",["EMO_SAD"]],
SIT046:["A parent scolded you harshly",["EMO_SAD","EMO_ASHAMED"]],
SIT048:["Not invited to a birthday party",["EMO_LEFT_OUT","EMO_SAD"]],
SIT049:["Fell down and has to decide whether to try again",["EMO_SCARED","EMO_UNSURE"]],
SIT050:["Missing a parent who travels a lot",["EMO_SAD","EMO_GRIEVING"]],
SIT051:["A close friend moved away",["EMO_SAD","EMO_GRIEVING"]],
SIT052:["Moving out of their bedroom",["EMO_SAD","EMO_WORRIED"]],
SIT054:["A big event they were excited for got cancelled",["EMO_DISAPPOINTED","EMO_SAD"]],
SIT055:["Saw another child crying",["EMO_SAD"]],
SIT056:["Left out of a group chat",["EMO_LEFT_OUT"]],
SIT057:["Not picked for a special role at school",["EMO_DISAPPOINTED","EMO_SAD"]],
SIT060:["Trying to help but getting into trouble",["EMO_GUILTY","EMO_FRUSTRATED"]],
SIT061:["Made a mistake in front of the whole class",["EMO_EMBARRASSED"]],
SIT062:["Forgot someone's name",["EMO_EMBARRASSED"]],
SIT063:["A peer made a comment about their body",["EMO_ASHAMED","EMO_EMBARRASSED"]],
SIT064:["Feeling self-conscious about new glasses",["EMO_ASHAMED","EMO_EMBARRASSED"]],
SIT065:["Worried about a new pimple",["EMO_ASHAMED"]],
SIT066:["Standing out for being the shortest or tallest",["EMO_ASHAMED","EMO_COMPARING"]],
SIT067:["Slower at reading than their classmates",["EMO_ASHAMED"]],
SIT068:["Picked last for a team",["EMO_ASHAMED","EMO_SAD"]],
SIT069:["Their clothes don't feel as 'cool' as others'",["EMO_ASHAMED","EMO_COMPARING"]],
SIT072:["Their project got no likes or views",["EMO_ASHAMED","EMO_SAD"]],
SIT073:["A drawing didn't turn out how they imagined",["EMO_FRUSTRATED","EMO_ASHAMED"]],
SIT074:["Corrected in front of friends or guests",["EMO_EMBARRASSED"]],
SIT075:["Forgot their lines in a play",["EMO_EMBARRASSED","EMO_NERVOUS"]],
SIT076:["Told their work looked messy",["EMO_ASHAMED"]],
SIT077:["Compared to a cousin or friend",["EMO_ASHAMED","EMO_COMPARING"]],
SIT082:["Their best friend is playing with someone else",["EMO_JEALOUS","EMO_LEFT_OUT"]],
SIT083:["A friend got a new toy",["EMO_JEALOUS","EMO_COMPARING"]],
SIT084:["A classmate won an award they wanted",["EMO_JEALOUS","EMO_DISAPPOINTED"]],
SIT085:["Someone else got to go first",["EMO_FRUSTRATED","EMO_DISAPPOINTED"]],
SIT086:["A parent was on a work call when they had news to share",["EMO_FRUSTRATED","EMO_LEFT_OUT"]],
SIT087:["Wanted the birthday gifts at a friend's party",["EMO_JEALOUS"]],
SIT088:["A friend is naturally better at a sport",["EMO_JEALOUS","EMO_COMPARING"]],
SIT089:["A new baby is getting all the attention",["EMO_JEALOUS","EMO_LEFT_OUT"]],
SIT090:["A classmate got the teacher's praise instead",["EMO_JEALOUS","EMO_COMPARING"]],
SIT091:["A friend has more followers online",["EMO_JEALOUS","EMO_COMPARING"]],
SIT092:["A friend went on a fancy vacation",["EMO_JEALOUS","EMO_COMPARING"]],
SIT093:["Wishing they had someone else's hair",["EMO_COMPARING","EMO_ASHAMED"]],
SIT094:["Wanted what was in a friend's lunchbox",["EMO_JEALOUS"]],
SIT095:["A friend has a later bedtime",["EMO_JEALOUS","EMO_COMPARING"]],
SIT096:["Wearing an older sibling's old clothes",["EMO_ASHAMED","EMO_COMPARING"]],
SIT097:["Still full of energy after a big party",["EMO_OVERWHELMED"]],
SIT098:["Can't focus after too much screen time",["EMO_OVERWHELMED"]],
SIT099:["A noisy, crowded mall feels like too much",["EMO_OVERWHELMED"]],
SIT100:["Too many activities packed into one day",["EMO_OVERWHELMED","EMO_CRANKY"]],
SIT101:["A long wait with nothing to do",["EMO_BORED","EMO_FRUSTRATED"]],
SIT102:["Stuck indoors on a rainy day",["EMO_BORED"]],
SIT103:["Their brain feels full after a long school week",["EMO_OVERWHELMED","EMO_CRANKY"]],
SIT104:["Cranky after a bad night's sleep",["EMO_CRANKY","EMO_FRUSTRATED"]],
SIT105:["Trying to do homework with the TV on",["EMO_FRUSTRATED"]],
SIT106:["Too many choices for one treat",["EMO_UNSURE","EMO_OVERWHELMED"]],
SIT107:["Told to 'be good' before an important event",["EMO_WORRIED","EMO_NERVOUS"]],
SIT108:["Waiting a long time for a turn on the swings",["EMO_FRUSTRATED","EMO_BORED"]],
SIT109:["Had to stop playing to do homework",["EMO_FRUSTRATED"]],
SIT110:["Cranky and hungry before dinner",["EMO_CRANKY"]],
SIT111:["Distracted by an uncomfortable classroom",["EMO_OVERWHELMED","EMO_FRUSTRATED"]],
SIT112:["Waiting for something exciting to happen",["EMO_UNSURE"]],
SIT113:["Struggling to learn a hard new topic",["EMO_FRUSTRATED","EMO_WORRIED"]],
SIT114:["Moving to a new home",["EMO_SAD","EMO_WORRIED"]],
SIT115:["Moving to a new country",["EMO_WORRIED","EMO_SAD"]],
SIT116:["Parents separating",["EMO_WORRIED","EMO_SAD"]],
SIT117:["A parent's new work schedule means less time together",["EMO_SAD","EMO_WORRIED"]],
SIT118:["Starting at a brand new school",["EMO_NERVOUS","EMO_UNSURE"]],
SIT119:["Their favourite teacher is leaving",["EMO_SAD","EMO_WORRIED"]],
SIT120:["A regular activity was suddenly cancelled",["EMO_DISAPPOINTED"]],
SIT121:["Summer ending and school starting again",["EMO_SAD","EMO_WORRIED"]],
SIT122:["Noticing a change in their body",["EMO_WORRIED","EMO_UNSURE"]],
SIT123:["A friend is suddenly acting different",["EMO_UNSURE","EMO_WORRIED"]],
SIT124:["A favourite app or game suddenly looks different",["EMO_FRUSTRATED","EMO_UNSURE"]],
SIT125:["A new helper joined the family",["EMO_UNSURE","EMO_WORRIED"]],
SIT126:["Hearing about an upcoming medical procedure",["EMO_WORRIED","EMO_SCARED"]],
SIT127:["The family is cutting back on treats for a while",["EMO_DISAPPOINTED","EMO_WORRIED"]],
SIT128:["Waiting anxiously for exam results",["EMO_WORRIED","EMO_NERVOUS"]],
SIT129:["Staying overnight away from home for the first time",["EMO_NERVOUS","EMO_SAD"]],
SIT130:["A favourite hobby is coming to an end",["EMO_SAD"]],
SIT131:["Overheard grown-ups mention a big change coming",["EMO_WORRIED","EMO_UNSURE"]],
SIT132:["Told a lie and feels bad about it",["EMO_GUILTY"]],
SIT133:["Tempted to steal something",["EMO_TORN","EMO_GUILTY"]],
SIT134:["Watched someone get bullied and didn't step in",["EMO_GUILTY","EMO_SCARED"]],
SIT135:["Someone unkind got praised instead",["EMO_ANGRY","EMO_CONFUSED_RIGHT_WRONG"]],
SIT136:["Wants to play but knows they should study",["EMO_TORN"]],
SIT137:["Tempted to look at a friend's test answers",["EMO_TORN","EMO_GUILTY"]],
SIT138:["Told a secret that feels too big to keep",["EMO_TORN","EMO_WORRIED"]],
SIT139:["Broke something and hid it",["EMO_GUILTY"]],
SIT140:["Noticed another child doesn't have basic things",["EMO_CONFUSED_RIGHT_WRONG","EMO_SAD"]],
SIT141:["Saw a grown-up break their own rule",["EMO_CONFUSED_RIGHT_WRONG"]],
SIT142:["Someone online asked for their password",["EMO_UNSURE","EMO_SCARED"]],
SIT143:["Saw someone litter",["EMO_ANGRY","EMO_CONFUSED_RIGHT_WRONG"]],
SIT144:["Saw a stray animal being treated badly",["EMO_SAD","EMO_CONFUSED_RIGHT_WRONG"]],
SIT145:["Broke a promise to a friend",["EMO_GUILTY","EMO_SAD"]],
SIT146:["Feels bad for leaving someone out of play",["EMO_GUILTY"]],
SIT147:["A friend said something hurtful about their culture",["EMO_ASHAMED","EMO_ANGRY"]],
SIT148:["Found something that isn't theirs",["EMO_TORN"]],
SIT149:["Overheard grown-ups talk about something unfair in the world",["EMO_WORRIED","EMO_CONFUSED_RIGHT_WRONG"]],
SIT150:["Their best friend made a new best friend",["EMO_JEALOUS","EMO_LEFT_OUT"]],
SIT151:["Friends aren't replying to their messages",["EMO_WORRIED","EMO_LEFT_OUT"]],
SIT152:["Accidentally left out of a game",["EMO_LEFT_OUT","EMO_SAD"]],
SIT153:["Friends made a plan without telling them",["EMO_LEFT_OUT","EMO_SAD"]],
SIT154:["A friend copied their idea",["EMO_ANGRY","EMO_FRUSTRATED"]],
SIT155:["Lost a game while their friend won",["EMO_DISAPPOINTED","EMO_JEALOUS"]],
SIT156:["A friend broke a promise to them",["EMO_SAD","EMO_ANGRY"]],
SIT157:["Rumours are being spread about them",["EMO_EMBARRASSED","EMO_ANGRY"]],
SIT158:["A friend apologised after hurting them",["EMO_SAD","EMO_UNSURE"]],
SIT159:["Accidentally hurt a friend's feelings",["EMO_GUILTY","EMO_SAD"]],
SIT160:["Asked to choose between two friends",["EMO_TORN"]],
SIT161:["Made a mistake that lost the game for the team",["EMO_GUILTY","EMO_ASHAMED"]],
SIT162:["A teammate isn't doing their part",["EMO_FRUSTRATED"]],
SIT163:["A friend got the pet they always wanted",["EMO_JEALOUS"]],
SIT164:["A younger child wants to join their game",["EMO_TORN","EMO_LEFT_OUT"]],
SIT165:["A friend is nervous before a performance",["EMO_NERVOUS","EMO_WORRIED"]],
SIT166:["A new classmate is sitting alone",["EMO_LEFT_OUT","EMO_UNSURE"]],
SIT167:["A friend keeps interrupting them",["EMO_FRUSTRATED"]],
SIT168:["Everyone in your group wants a different idea",["EMO_FRUSTRATED","EMO_TORN"]]
};

// Pronoun pass: parentLabel is parent-facing UI, locked to second-person "your/you"
// wherever the pronoun refers to THIS child. Left untouched where "their/they" refers
// to someone else in the scene (a friend, sibling, teammate, grown-up) — changing those
// would corrupt meaning (e.g. SIT162 "a teammate isn't doing their part" stays as-is).
const PRONOUN_FIXES = {
  SIT001: "Someone won't share the toy you're playing with",
  SIT002: "Screen time ended before you were ready",
  SIT005: "Couldn't finish your homework",
  SIT007: "Someone broke something you built",
  SIT010: "Blamed for something you didn't do",
  SIT012: "No say in what you had to wear",
  SIT013: "An adult didn't understand what you meant",
  SIT018: "A sibling told on you unfairly",
  SIT019: "Your clothes felt scratchy and uncomfortable",
  SIT036: "Afraid the class will laugh at you",
  SIT042: "A friend didn't want to play with you today",
  SIT043: "Your pet died",
  SIT045: "Lost your favourite toy or blanket",
  SIT052: "Moving out of your bedroom",
  SIT054: "A big event you were excited for got cancelled",
  SIT063: "A peer made a comment about your body",
  SIT067: "Slower at reading than your classmates",
  SIT069: "Your clothes don't feel as 'cool' as others'",
  SIT072: "Your project got no likes or views",
  SIT073: "A drawing didn't turn out how you imagined",
  SIT075: "Forgot your lines in a play",
  SIT076: "Told your work looked messy",
  SIT082: "Your best friend is playing with someone else",
  SIT084: "A classmate won an award you wanted",
  SIT086: "A parent is busy when you want to share something",
  SIT093: "Wishing you had someone else's hair",
  SIT103: "Your brain feels full after a long school week",
  SIT119: "Your favourite teacher is leaving",
  SIT122: "Noticing a change in your body",
  SIT136: "Wants to play instead of studying",
  SIT142: "Someone online asked for your password",
  SIT147: "A friend said something hurtful about your culture",
  SIT148: "Found something that isn't yours",
  SIT150: "Your best friend made a new best friend",
  SIT151: "Friends aren't replying to your messages",
  SIT153: "Friends made a plan without telling you",
  SIT154: "A friend copied your idea",
  SIT155: "Lost a game while your friend won",
  SIT156: "A friend broke a promise to you",
  SIT157: "Rumours are being spread about you",
  SIT158: "A friend apologised after hurting you",
  SIT164: "A younger child wants to join your game",
  SIT167: "A friend keeps interrupting you"
};
Object.keys(PRONOUN_FIXES).forEach(id => { MAP[id][0] = PRONOUN_FIXES[id]; });

const activeIds = frozen.situations.map(s => s.id);
const mapKeys = Object.keys(MAP);
const missing = activeIds.filter(id => !mapKeys.includes(id));
const extra = mapKeys.filter(id => !activeIds.includes(id));
console.log('missing from MAP:', missing);
console.log('extra in MAP (not active):', extra);
if (missing.length || extra.length) { throw new Error('MAP does not match active set 1:1'); }

const out = {
  _meta: {
    status: "DRAFT — Step 3 for review. Does NOT touch the frozen 156 situation seeds (situationSeed data unchanged, only new fields appended for review). Not written to live situations.json.",
    activeCount: 156,
    emotionCount: EMOTIONS.length
  },
  emotions: EMOTIONS,
  situations: frozen.situations.map(s => {
    const src = source.find(x => x.id === s.id);
    const [parentLabel, emotionIds] = MAP[s.id];
    return {
      id: s.id,
      title: s.title,
      parentLabel,
      storySeed: s.storySeed,
      emotionIds,
      lifeDomainIds: src.hard.life_domain_ids
    };
  })
};

fs.writeFileSync(outPath, JSON.stringify(out, null, 2) + '\n');
console.log('Wrote', outPath, 'with', out.situations.length, 'situations and', EMOTIONS.length, 'emotions.');
